root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
extends: 
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:@typescript-eslint/strict"
  - "plugin:unicorn/recommended"
  - "prettier"
plugins: 
  - "@typescript-eslint"
  - "eslint-plugin-tsdoc"
env:
  es2021: true
rules:
  unicorn/no-null: "off"
  unicorn/no-useless-undefined: "off"
  tsdoc/syntax: "warn"
  # TODO: Clean these up
  "@typescript-eslint/no-floating-promises": "off"
  "@typescript-eslint/no-misused-promises": "off"
