root: true
parser: "@typescript-eslint/parser"
extends: 
  -  "eslint:recommended"
  -  "plugin:@typescript-eslint/recommended"
  -  "plugin:unicorn/recommended"
  -  "prettier"
plugins: 
  - "@typescript-eslint"
env:
  es2021: true
