root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
extends: 
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:@typescript-eslint/strict"
  - "plugin:unicorn/recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:react-hooks/recommended"
  - "prettier"
plugins: 
  - "@typescript-eslint"
  - "eslint-plugin-tsdoc"
env:
  es2021: true
rules:
  unicorn/no-null: "off"
  unicorn/no-useless-undefined: "off"
  tsdoc/syntax: "warn"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-invalid-void-type": "off"
overrides:
  - files:
      - "*.{,c,m}js{,x}"
    rules:
      tsdoc/syntax: "off"
  - files:
      - "tailwind.config.cjs"
    env:
      node: true